language: node_js
node_js:
  - node

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

before_install: yarn global add greenkeeper-lockfile@2
install: yarn install

before_script: greenkeeper-lockfile-update
script:
  - yarn lint
  - yarn flow
  - yarn test
  - yarn coverage
  - yarn build
after_script: greenkeeper-lockfile-upload

before_deploy: yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target-branch: gh-pages
  local-dir: example/dist
  on:
    branch: master
