language: node_js
node_js:
  - node

cache:
  yarn: true
  directories:
    - node_modules

before_install: yarn global add greenkeeper-lockfile@1
install: yarn install

before_script: greenkeeper-lockfile-update
script:
  - yarn lint
  - yarn flow
  - yarn test
after_script: greenkeeper-lockfile-upload

before_deploy: yarn build
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    target-branch: gh-pages
    local-dir: example/dist
    on:
      branch: master