name: lint-test-build

description: Lint, test, build

inputs:
  CODECOV_TOKEN:
    description: 'Codecov token'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
      shell: bash
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn install
      shell: bash
    - run: yarn lint
      shell: bash
    - run: yarn test:coverage
      shell: bash
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ inputs.CODECOV_TOKEN }}
        directory: ./coverage
    - run: yarn build
      shell: bash
