name: pull-request

on: pull_request

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/lint-test-build
        with:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
